#!/usr/bin/env python

"""
Entry point for the program. Includes an import for the FrotEnd and the
Player classes, as well as curses.
"""
from front.FrontEnd import FrontEnd
from player.Player import Player
from curses import wrapper

def main():
    player = Player()
    front_end = FrontEnd(player)

if __name__ == "__main__":
    main()
